"""
The icon names the UI asks for, in one place.

The icons are the app's own (`icons/hicolor/scalable/actions/`, generated by
`tools/make_icons.py`), so the interface looks the same whatever icon theme a
board has. `register()` puts `icons/` on the icon theme's search path.
"""

import os

from gi.repository import Gdk, Gtk

APP = "org.interaktiv.School"


def _icon(name: str) -> str:
    return f"interaktiv-{name}-symbolic"


# navigation
BACK = _icon("back")
PREV_PAGE = _icon("chevron-left")
NEXT_PAGE = _icon("chevron-right")
UP = _icon("chevron-up")
DOWN = _icon("chevron-down")
CANCEL = _icon("close")
CHECK = _icon("check")
MORE = _icon("more")

# library
BOOK = _icon("book")
INSTALL = _icon("download")
UNINSTALL = _icon("trash")
EDIT = _icon("edit")
REFRESH = _icon("refresh")
SEARCH = _icon("search")

# reader
ZOOM_IN = _icon("zoom-in")
ZOOM_OUT = _icon("zoom-out")
FIT_PAGE = _icon("fit-page")
FIT_WIDTH = _icon("fit-width")
ROTATE = _icon("rotate")
THEME = _icon("theme")
FULLSCREEN = _icon("fullscreen")
RESTORE = _icon("restore")
MODE_BOOK = _icon("view-book")
MODE_SINGLE = _icon("view-single")
MODE_SCROLL = _icon("view-scroll")

# sidebar
CONTENTS = _icon("contents")
SIDEBAR = _icon("sidebar")
PAGES = _icon("pages")
BOOKMARK = _icon("bookmark")
ACTIVITIES = _icon("activities")

# activities
PLAY = _icon("play")
BOLT = _icon("bolt")
BROWSER = _icon("open-external")

# help and input
HELP = _icon("help")
INFO = _icon("info")
BACKSPACE = _icon("backspace")


ICON_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "icons")


def app_icon_path() -> str:
    return os.path.join(ICON_DIR, "hicolor", "scalable", "apps", f"{APP}.svg")


def register() -> None:
    """Put the app's own icons on the icon theme's search path."""
    if not os.path.isdir(ICON_DIR):
        return
    display = Gdk.Display.get_default()
    if display is None:
        return
    Gtk.IconTheme.get_for_display(display).add_search_path(ICON_DIR)
